# https://github.com/devapro/compose-desktop-demo
FROM amd64/ubuntu
WORKDIR /app
RUN apt-get update && apt-get upgrade -y
RUN apt install wget -y
RUN apt install dpkg -y
RUN apt install java-common -y
RUN apt install openjdk-17-jre -y
RUN apt install openjdk-17-jdk -y
RUN apt install binutils -y
RUN apt install fakeroot -y
RUN apt install libdpkg-dev -y
